services:
  - type: web
    name: crypto-adviser-api
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "pip install -r api/requirements.txt"
    startCommand: "cd api && python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
